# config/database.yml

default_sqlite: &default_sqlite
  adapter: sqlite3
  pool:    <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default_sqlite
  database: db/development.sqlite3

test:
  <<: *default_sqlite
  database: db/test.sqlite3

production:
  adapter: postgresql
  url:     <%= ENV['DATABASE_URL'] %>
